name: CI
on:
  pull_request:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install modules
        run: npm install
      - name: run ESLint
        run: npm run eslint
      - name: run Prettier
        run: npm run prettier-check
      - name: run Code Quality
        run: echo "still working"
      - name: run Jest Tests
        run: npm run test
      - name: check Jest test coverage
        run: echo "still working on it"
      - name: Cypress Testing
        run: echo "still working on it"
